### ISSUE TITLE
Bug: sdk list java -> missing status of installed versions

### ISSUE THREAD

**Issue by javiroman** [sdkman/sdkman-cli#1052]
**Bug report**
"sdk list java" usually list a column with the installed versions

```
$ sdk list java
=================================================================
Available Java Versions
=================================================================
 Vendor    | Use | Version | Dist    | Status    | Identifier
-----------------------------------------------------------------
 ...
 Azul Zulu | >>> | 14.0.1  | adpt    | installed | 14.0.1.j9-adpt
 ...
```
However I'm getting this column empty, from the last update from SDKMAN 5.13.1 to SDKMAN 5.13.2.

**To reproduce**
```
$ sdk version

SDKMAN 5.13.2
$ ls .sdkman/candidates/java/
11.0.11.hs-adpt/  8.0.292.hs-adpt/  current@
$ sdk current java

Using java version 11.0.11.hs-adpt
$ sdk list java | grep installed
(empty)
```

**System info**
```
$ cat /etc/fedora-release 
Fedora release 35 (Thirty Five)
$ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
```

**Comment by javiroman** [comment]
Ok, the **Dist** **adpt** (AdoptOpenJDK) is not available any more? That's the problem.

**Comment by marc0der** [comment]
Hi @javiroman, we've removed AdoptOpenJDK as it moved to the Eclipse foundation as Adoptium Temurin. Since we no longer support AdoptOpenJDK we will not be displaying it in our Java list view anymore.

I also don't think this is a bug in the CLI so closing this issue as per our [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/1d65017c150a01cd3ea36f7a61628c5683ce238a/CONTRIBUTING.md).
