### ISSUE TITLE
Bug: [Invalid default candidate for Java 17]

### ISSUE THREAD

**Issue by aivantsov** [sdkman/sdkman-cli#1097]
**Bug report**

Current available Java 17 Temurin version is `17.0.3-tem`. However, when installing default Java version or upgrading `sdk` suggests `17.0.2-tem`

**To reproduce**

```
sdk ls java | grep -E 17.+tem
               | >>> | 17.0.3       | tem     | installed  | 17.0.3-tem          
Omit Identifier to install default version 17.0.2-tem:
    $ sdk install java 17.0.2-tem
```
The REST API call is not returning the expected version `17.0.3-tem`:

```
echo $(curl -s https://api.sdkman.io/2/candidates/default/java)
17.0.2-tem
```

See also https://github.com/sdkman/sdkman-cli/issues/815.

**System info**

- OS (e.g. Windows, Linux, Mac, Cygwin, WSL, etc.) and version
```
uname -a
Darwin 157278S0 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64
```
- Shell and version (e.g. `bash --version`/`zsh --version`)
```
zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
```
- The output of `sdk version`
```

SDKMAN 5.15.0
```

**Comment by marc0der** [comment]
Hi @aivantsov, this is usually caused by a data issue when a release is performed but not set to default for a candidate. I've now corrected this in our database.

Please feel free to chat with us on Slack as per the [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/9f86a554692e41406e880d7db122df71006afa09/CONTRIBUTING.md) prior to opening a bug report here.
