### ISSUE TITLE
Bug: "java 17.0.4-tem" not available on Macs, but offered as default

### ISSUE THREAD

**Issue by ksilz** [sdkman/sdkman-cli#1106]
**Bug report**
Temurin 17.0.4 is not available on macOS - see screenshots below.

![image](https://user-images.githubusercontent.com/1061209/180462517-cd6d5575-9c19-4fdb-86fe-4d09c04b2dff.png)

![image](https://user-images.githubusercontent.com/1061209/180462558-0749262b-6138-48d8-b208-3571be324b51.png)

But SDKMAN! still offers it as the default: 

![image](https://user-images.githubusercontent.com/1061209/180463604-8458344e-9c0e-4f50-9fff-209ab935aeb5.png)

**To reproduce**
- On macOS, enter `sdk install java`.
- You'll get this error:

![image](https://user-images.githubusercontent.com/1061209/180462617-7e8232e5-dd15-4759-8527-e9193d5bcb0d.png)

**System info**
- macOS 12.5 on MacBook Pro (16-inch, 2021) with M1 Max
- zsh 5.8.1 (x86_64-apple-darwin21.0)
- SDKMAN 5.15.0

**Comment by ksilz** [comment]
Eclipse Temurin [staggers its releases](https://github.com/adoptium/adoptium/issues/153) over a couple of weeks, it seems.

**Comment by marc0der** [comment]
The Java default has now been corrected to point at 11.0.3-tem.
/cc @eddumelendez

**Comment by eddumelendez** [comment]
every vendor has a different release process. Usually, temurin used to do it in a week. 17.0.4-tem is available for other OS already but not for macos as far as I can see. The default version is now automatic so we need a different way to do it to cover this case.

**Comment by tellison** [comment]
> every vendor has a different release process. Usually, temurin used to do it in a week. 17.0.4-tem is available for other OS already but not for macos as far as I can see. The default version is now automatic so we need a different way to do it to cover this case.

Correct. Adoptium prioritises the platforms and versions in a release, and makes them available as soon as they are ready rather than waiting for them all to complete. Some platforms take longer due to the speed of running tests, and/or the number of resources (people/machines) available to work on them during the release process.

We always show the status of each platform release in [a public issue](https://github.com/adoptium/adoptium/issues/153), and here's [a handy timeline](https://github.com/adoptium/adoptium/issues/157) showing the current platform release skew.

The [Adoptium API](https://api.adoptium.net/q/swagger-ui/) is the most reliable way to tell you which release is the latest, and if any particular platform/version/release is available. We use that API to power the website etc. too.

Keep up the good work on sdkman! As always, feel free to ask for anything we can do that will make your life easier. :-)

**Comment by eddumelendez** [comment]
@tellison thanks for sharing! this is really useful information
