### ISSUE TITLE
Improvement: Verify that `tar` is available

### ISSUE THREAD

**Issue by gunnarmorling** [sdkman/sdkman-cli#1267]
I just tried to use SDKMan on a fresh Linux install, and it would keep failing on me with this message:

```
Download has failed, aborting!
```

Enabling debug logging didn't provide any further insight about the cause. Only when inspecting the post-install hook, I realized that the issue was that the `tar` command wasn't available on this environment yet.

**Comment by marc0der** [comment]
Ah, good catch! That's because `tar` is only used in the installation hooks, not in the CLI. I'd be happy to have it added it to the install script as a pre-requisite. If you feel up to it, you could even contribute that change yourself over here:
https://github.com/sdkman/sdkman-hooks/blob/master/app/views/includes/sanity.scala.txt

**Comment by gunnarmorling** [comment]
Sure thing: https://github.com/sdkman/sdkman-hooks/pull/62
