### ISSUE TITLE
Question: support for russian developers

### ISSUE THREAD

**Issue by yermilov** [sdkman/sdkman-cli#1272]
- [x] I have checked [the documentation](https://sdkman.io/usage)
- [x] I have done a quick search in [past issues](https://github.com/rclone/rclone/issues?q=) or [Stack Overflow](https://stackoverflow.com/questions/tagged/sdkman) for similar problems
- [ ] I have brought up a conversation in the [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues)

**Question**
Hello team! I'm a long-time [backer for SDKMAN!](https://opencollective.com/yaroslav-yermilov) and want to raise an important issue. I was browsing the documentation today looking for a way to remove SDKMAN! and re-install it from scratch. In the process, I stumble across this FAQ - https://github.com/sdkman/sdkman-cli/wiki/FAQ#im-located-in-russia-and-sdkman-always-reports-that-the-internet-is-not-available-is-the-service-down. This is very insensitive and offensive for a lot of people of the free world. Moreover, you are suggesting a way to evade extensive sanctions (https://blogs.microsoft.com/on-the-issues/2022/03/04/microsoft-suspends-russia-sales-ukraine-conflict/, https://blog.adobe.com/en/publish/2022/03/04/adobe-stops-all-new-sales-in-russia, https://www.politico.eu/article/apple-pulls-products-from-russia/, ...) and support for the developers that are considered ["foundation of war effort"](https://kyivindependent.com/how-russias-liberal-tech-companies-became-foundation-of-putins-war-effort/).

Right now, it may look like you take a stance in the ongoing war on the russia side. If it is not your intention, please clarify them in the FAQ, joining a lot of other dev tools in their support for Ukraine (https://twitter.com/junitteam, https://blog.jetbrains.com/blog/2022/03/11/jetbrains-statement-on-ukraine/, https://github.com/vshymanskyy/StandWithUkraine?tab=readme-ov-file#projects-that-standwithukraine). If you don't want to take a stance - don't take it and remove this FAQ section from your documentation.

Thank you!

**Comment by marc0der** [comment]
Hi @yermilov!

Thanks for the message and for making me aware of this. I apologise if this FAQ entry has caused you or anyone else offence. As a bit of background, I wrote that FAQ entry a few years ago before there was even mention of war. At the time, many Russian developers were reporting that they could no longer access our APIs for reasons unknown. This restriction of internet access was an ominous forerunner of things yet to come. I wrote the FAQ entry so I wouldn't need to explain things repeatedly.

I have now updated the FAQ so that Russia is no longer mentioned. I will still mention the use of VPNs to access our APIs for people who find themselves in organisations or countries where their personal liberties are removed through restriction of internet access.

Again, apologies, thanks for making me aware of this and for your continued support!
