### ISSUE TITLE
Bug: JAVA_HOME not defined for GUI apps on Linux (Gnome)

### ISSUE THREAD

**Issue by sonicdebris** [sdkman/sdkman-cli#1278]
Not sure this is an issue with sdkman and if this is the right place to post it, but I thought it would be of interest.

**Bug report**
The JAVA_HOME as set by sdkman is not available to GUI applications on Linux with Gnome Shell.

**To reproduce**
- Install Android Studio (using Jetbrains Toolbox)
- In Settings -> Build, Execution, Deployment -> Gradle, click on the Gradle JDK selection box
- Look at the value for JAVA_HOME -> it doesn't match the one set by sdkman

**Workaround**
- On X11, export the variable in `.profile`
- On Wailand, define the variable in `.config/environment.d/envvars.conf`

**More context**
https://issuetracker.google.com/issues/162313337

**System info**
Ubuntu (Pop_OS) and Arch (Manjaro), with gnome shell, both Wayland and X11

**Comment by sonicdebris** [comment]
Yes it makes sense. It would still be nice if at least `sdk default` could influence the "UI shell" as well, but I guess that with the workarounds I am using already it's not such a big deal.

**Comment by marc0der** [comment]
Unfortunately we don't have control of anything outside of the shell since it's purely a bash process.

However, my suggestion would be to use the `current` symlink under the java candidate to set up such a system wide alias as that tracks the default. Alternatively you can use the `sdk home` command to infer this location.
