### ISSUE TITLE
Bug: `upgrade` command doesn't upgrade but wants to set a default version

### ISSUE THREAD

**Issue by audio-engineer** [sdkman/sdkman-cli#1319]
**Bug report**

I have Amazon Corretto 23.0.0.37.1 installed using the `23-amzn` ID, and since version 23.0.1.8.1 just came out, I wanted to upgrade, but the `upgrade` subcommand behaves really strangely. Instead of upgrading a version, it instead prompts you to set a default version, which I don't want. So when entering `n` it just exits without doing anything. Entering `Y` it installs the suggested version instead of upgrading the already installed version:
```shell
~ ❯ sdk upgrade java

Available defaults:
java (local: 23-amzn; default: 21.0.4-tem)

Use prescribed default version(s)? (Y/n): n
~ ❯
```
**To reproduce**

Run the `sdk upgrade java` command
**System info**

- macOS 15.0.1
- zsh 5.9
```shell
~ ❯ sdk version

SDKMAN!
script: 5.18.2
native: 0.4.6
```

**Comment by marc0der** [comment]
Hi @audio-engineer, this isn't a bug. We currently track Temurin as our sensible default for upgrades (Temurin is the defacto OpenJDK used by most folks).

We have had several requests that people want to track a specific vendor's JDK releases (like Amazon in your case) but we haven't implemented it yet because it's complicated. We are working towards this, though.

In future, please chat to us on Discord as per our contributing guidelines before opening a bug report here. Thanks!
