### ISSUE TITLE
Support per directly local settings

### ISSUE THREAD

**Issue by ggascoigne** [sdkman/sdkman-cli#219]
Following the pattern of rbenv and jenv it would be awfully convenient if gvm had the ability to store local configuration options that take precedence over the global ones on a per project basis.

**Comment by valerius** [comment]
+1 for .rvm like commands. Because the point of GVM and the like is to manage multiple version of development tools, doing so transparently seems like the next step in evolution. The alternative is to assume the developer manually switch to get their project to work, which if thats mandatory, why do we have to wait for a compile or other exception to notify us of what we should have done, when such change could have been done on our behalf if a particular file (e.g. .gvm-versions) exists there, otherwise using the default. Such I have found useful in the ruby world,  though I suppose a case can be made for the existing alternative, Im just not sure of technical benefits anymore than I'm privy to the alternative ramifications, etc. Just the same, thanks for the great work!

**Comment by marc0der** [comment]
Not sure, but are you confusing us with the Go Version Manager?
This is the SDKMAN, formerly GVM, the Groovy enVironment Manager.

**Comment by valerius** [comment]
Forgive the confusion, I'm using GVM (now sdkman) for grails development primarily, though it supports multiple sdks and desired such support generally speaking. I think I may have referenced this in the go version manager issue, but admittedly didn't realize it was different. My mistake :)

**Comment by marc0der** [comment]
No prob, you are in the right place then.

The following issue was raised a few days ago which relates directly to this:
https://github.com/sdkman/sdkman-extensions/issues/9
