### ISSUE TITLE
gvm not quite working on zsh

### ISSUE THREAD

**Issue by joshlong** [sdkman/sdkman-cli#271]
i did a fresh `gvm` installation, then closed all my shells. then opened it again and did `gvm install lazybones`. then i tried to use `lazybones` and it, nor any of the other candidates, were on the PATH.

**Comment by StanSvec** [comment]
Just an update. For sdkman this works in my case when added to ~/.zshrc:
```bash
[[ -s ~/.sdkman/bin/sdkman-init.sh ]] && source ~/.sdkman/bin/sdkman-init.sh
```
Without double quotes..

**Comment by marc0der** [comment]
The double quotes are used to escape spaces in edge cases where users have spaces in folder names.

Apart from that it does not affect anything, and is considered good practice to always use them when expressing paths in bash.

**Comment by StanSvec** [comment]
Now I see. Thanks for the explanation. It didn't work for me, because I used `~` sign as a shortcut for my home dir. So this doesn't work:
```bash
[[ -s "~/.sdkman/bin/sdkman-init.sh" ]] && source "~/.sdkman/bin/sdkman-init.sh"
```
but this works fine:
```bash
[[ -s "/home/stan/.sdkman/bin/sdkman-init.sh" ]] && source "/home/stan/.sdkman/bin/sdkman-init.sh"
```
Or with `~` as mentioned above, but without quotes. Obviously bash and linux programming is not my area of expertise. :) So now I presume that signs like this `~` are not interpreted as special characters when used in a string enclosed by double quotes.
