### ISSUE TITLE
What Windows users should do? was  [Feature request] installer for Windows

### ISSUE THREAD

**Issue by paulvi** [sdkman/sdkman-cli#284]
as Windows does not go with standard `curl`, there should be installing option for Windows

**Comment by aruizca** [comment]
The instalation process completes on Windows if run using the [cmder tool](http://bliker.github.io/cmder/), but it does not update the PATH env variable effectively because the command on Windows is different. I will try to change the script to see if I can make it work on Windows using cmder.

Cheers,

**Comment by flofreud** [comment]
Cmder is a terminal host program based on ConEmu combined with clink. The default shell used in cmder is cmd.exe and not powershell.exe (I'm using Cmder's version of ConEmu with PowerShell).

The PoshGVM is client for the GVM-API is a PowerShell-port of the Bash-client which doesn't work with cmd.exe and also doesn't change the PATH variable of your system, but the PATH variable of an PowerShell session.

To the best of my knowledge there is no BATCH-based GVM client, which you could use in cmd.exe. You could use the Bash-client with Cygwin or you use the "new" shell for Windows (PowerShell).

**Comment by marcoVermeulen** [comment]
Yes that is right. We will not be providing or supporting a batch based
client. You can use POSH or the standard bash client on cygwin when using
windows. Git Bash is not supported either.

**Comment by djKianoosh** [comment]
FWIW, I was able to get gvm working in Windows using git bash.. just had to make a minor tweak to use the Windows utility ```junction.exe``` instead of "ln -s" when it wants to symlink the "current" directory:

so, in ```gvm-common.sh:L105```:
```
	#ln -s "${GVM_DIR}/${CANDIDATE}/${VERSION}" "${GVM_DIR}/${CANDIDATE}/current"
	junction "${GVM_DIR}/${CANDIDATE}/current" "${GVM_DIR}/${CANDIDATE}/${VERSION}"
```

junction.exe: https://technet.microsoft.com/en-us/sysinternals/bb896768.aspx

btw, there's such a thing as ```mklink``` in newer versions of Windows: 
http://superuser.com/questions/752538/mklink-vs-junction-exe
http://superuser.com/questions/550732/use-mklink-in-msys
```cmd //c mklink```
