### ISSUE TITLE
Add flag to install option to eagerly set candidate as default

### ISSUE THREAD

**Issue by mojavelinux** [sdkman/sdkman-cli#303]
After installing a candidate, gvm prompts the user about whether to set the candidate as the default. It would be helpful, especially for tutorials, if it were possible to answer this question eagerly.

Proposal:

```
gvm install gradle --default
```

I understand that it's possible to set gvm_auto_answer to accomplish the same goal. However, setting auto answer globally to cover this case is too heavyweight and also feels risky.

**Comment by marc0der** [comment]
Revisiting this request. Unfortunately I don't really see this ever making it into the SDKMAN CLI. We already have a lightweight confirmation (a simple tap on enter for default Y), or otherwise a configuration option bypassing it all together. Having a third way of dealing with confirmations would simply complicate something which is simple and works well.
