### ISSUE TITLE
autodetect SDK version and switch to it

### ISSUE THREAD

**Issue by donalmurtagh** [sdkman/sdkman-cli#410]
Many tools similar to sdkman detect the correct version of an SDK to use in a project based on the presence of a file in the project's root dir. For example jenv detects the JDK to use for a project based on the presence of a `.java-version` file in a project's root, and will then run the correct version of `javac`, `java`, etc. depending on which version is specified in this file.

I realise this is a more difficult task for sdk than say jenv, because sdk is responsible for managing multiple different SDKs.

**Comment by marc0der** [comment]
This has been spoken about many times in the past, and it was agreed upon that it would be best to have this implemented in the [sdkman-extensions](https://github.com/sdkman/sdkman-extensions) project. This is due to the fact that sdkman is (and always will be) agnostic to it's specific candidates.

Using the extension feature gives the closest possible experience to what tools like jenv currently do. The sample command provided in the project give an `sdk switch` command which will automatically switch to the correct candidate version.

Feel free to adapt this extension, and even consider reworking the existing one if need be. We would also be happy to accept pull requests for new extensions if you come up with a better one.

**Comment by marc0der** [comment]
No response so closing this issue.
