### ISSUE TITLE
502 bad gateway response

### ISSUE THREAD

**Issue by frangarcia** [sdkman/sdkman-cli#422]
When running the command:

`sdk list grails`

I am getting the response:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.14</center>
</body>
</html>
```

Trying the next command works fine:

`curl -s "api.sdkman.io/candidates/list"`

**Comment by ligun** [comment]
My PC occured similar problem.
But the command was different.
I execute next command.
```sdk list groovy```

The result was same message.

**Comment by busches** [comment]
Also getting this running Cygwin, looks to be a URL issue and if I change the regular expression that creates the URL to convert spaces to `%20`, in `function __sdkman_determine_current_version`, I'm able to get a successful response back.

`CURRENT=$(echo $PATH | sed -r "s|${SDKMAN_CANDIDATES_DIR}/${candidate}/([^/]+)/bin|!!\1!!|1" | sed -r "s|^.*!!(.+)!!.*$|\1|g" | sed -r "s|\s|%20|g")`

I'm not able to test to see if we need to add another if condition to the function for Cygwin specifically or if it's needed on Unix as well.

**Comment by busches** [comment]
Dug into this some more, the root cause, for me at least, is I have `grails` in another place on my path, ironically pointing to my old `.gvm` location, so when we check to see if the candidate is present: `present=$(__sdkman_path_contains "${candidate}")` we get a hit and it proceeds to try and replace it on the path, but at least on Cygwin, if sed has no capturing groups, which it doesn't as it's looking for `${SDKMAN_CANDIDATES_DIR}/${candidate}`, then it doesn't replace anything. Which results in the entire `path` being added to the query string resulting in a corrupt URL and the `502` error.

I believe the proper fix is to harden the check for present to:
`present=$(__sdkman_path_contains "${SDKMAN_CANDIDATES_DIR}/${candidate}")`
So we're looking for the path we're expecting to replace, instead of a portion of it.

@marc0der Let me know if this is the direction you want to go and I can submit a PR.

**Comment by marc0der** [comment]
I'd suggest that you remove the interference of the old GVM Grails first,
as this should not be on the path at all.

Also, the reason why we have the snippet as the last statement in your bash
profile should guarantee that sdkman's candidates appear earliest in the
path.

Could I ask you to a) remove any hints of GVM from your bash profile and b)
remove the old dot gvm folder completely.

Then let's reassess if we need any code changes to make it more defensive.

**Comment by busches** [comment]
Removing GVM fixes it yes, but anyone that has previously installed any candidate on their path, let's say Groovy through the Windows Installer that auto adds it to the PATH, will encounter this issue.

**Comment by marc0der** [comment]
Thanks for contributing. Let's see if this solves the problem you have been seeing.

I'll release the new version of the CLI later this weekend along with some other improvements.
