### ISSUE TITLE
skdman do not check the current installed groovy or gralde on my mac

### ISSUE THREAD

**Issue by WizardMerlin** [sdkman/sdkman-cli#473]
`brew install groovy `

and then add path in my ~/.zshrc the following:

```
export GROOVY_HOME=/usr/local/opt/groovy/libexec                                                                                  
export PATH=$PATH:$GROOVY_HOME/bin
```

after that, i restart the bash terminal

`sdk list groovy`

it seems that sdkman do not check the exsiting groovy version.

and i installed it using sdk man: 

`sdk install groovy 2.4.7`

and then `which groovy`
and i saw:
__/Users/Mac15/.sdkman/candidates/groovy/current/bin/groovy__

and gradle the same..

is a bug? 
how to solve it ? (i mean i have double copy in mac)

**Comment by marc0der** [comment]
Why would you install groovy with brew if you are using sdkman? I would remove the brew version and simply install it with sdkman.

Brew is not compatible with sdkman because we manage the GROOVY_HOME environment variable as well as the PATH dynamically. Any attempts to try managing the home variables will break things.

**Comment by WizardMerlin** [comment]
got it, i have uninstalled homebrew one. just using sdkman.

so far so good. thx.

**Comment by gezichenshan** [comment]
The GROOVY_HOME is dynamically, so how to set the libraries in~/.groovy/grapes into classpath?
