### ISSUE TITLE
Automatically accept Java license agreement when sdkman_auto_answer is true

### ISSUE THREAD

**Issue by nartamonov** [sdkman/sdkman-cli#537]
Currently sdkman forces to manually accept license agreement during installation of JDK, regardless of `sdkman_auto_answer` setting:

```
~$ sdk version
SDKMAN 5.1.18+191
~$ grep auto_answer ~/.sdkman/etc/config
sdkman_auto_answer=true
~$ sdk install java 8u121

Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n):
```

@marc0der [suggested](https://gitter.im/sdkman/user-issues?at=589af59af045df0a221f2c32) that is should be possible to fix it in pre-installation hook.

**Comment by MartinX3** [comment]
+1
Very important for me.

**Comment by marc0der** [comment]
AFAIK this would contravene the license agreement and make it illegal to
install the Oracle JDK. The agreement must be explicitly agreed to.

We could do something for Zulu JDKs though. Would this work for you?

**Comment by MartinX3** [comment]
Thank you. The Zulu SDK is fine to avoid the agreement. :)

But one problem is still there.
After installing a second java version, I need to press y/n to declare it to the default java version.
How I can automate this in a script?

**Comment by marc0der** [comment]
@MartinX3 You can bypass this by using a [configuration setting](http://sdkman.io/usage.html#config). `sdkman_auto_answer=true` is the one you're looking for.

**Comment by marc0der** [comment]
@nartamonov unfortunately we won't be able to address this in the pre-installation hook as we explicitly need to opt in to the Oracle Binary Code License Agreement. As discussed earlier in this thread, the Zulu JDK does not require this manual step, would this work for you too?

**Comment by marc0der** [comment]
Closing this issue as we cannot bypass this step for legal reasons.

**Comment by drrzmr** [comment]
```yes | sdk install java 8.0.201-oracle```

**Comment by marc0der** [comment]
@drrzmr This is illegal.

**Comment by mikelococo** [comment]
@marc0der It's clear that the BCL needs to be opt-in and explicitly accepted, but it there an explicit requirement somewhere that it must be opt-in exactly at the time of each download? Why must we forbid users from persisting their agreement in the sdkman config?

sdkman is already accepting a user-preference at download time when it prompts. It then immediately transmits that preference to Oracle on behalf of the user. Why can we not persist that same preference at config time via an explicit option like sdkman_accept_oracle_bcl which is documented as something like:

```
Oracle requires that you agree with the Oracle Binary Code License Agreement prior to installation.
The license agreement can be found at:

http://www.oracle.com/technetwork/java/javase/terms/license/index.html

When enabled, this setting will instruct sdkman to transmit to Oracle your acceptance of the BCL
each time an Oracle JDK or JRE is downloaded.
```

This scheme accepts the same user-preference, does not mix it in ambiguously with other no-prompt settings, and is explicitly opt-in. The only difference is that the acceptance is collected at configure time rather than download time.
