### ISSUE TITLE
Jenkins Grails plugin does not list lastest versions of Grails

### ISSUE THREAD

**Issue by stigmelling** [sdkman/sdkman-cli#563]
Looks like the Grails backend crawler (https://github.com/jenkinsci/backend-crawler/blob/master/grails.groovy) uses the list provided by http://api.sdkman.io/candidates/grails

The latest versions 3.2.8 and 2.5.6 are missing from the list.

**Comment by marc0der** [comment]
It turns out that this api endpoint was no longer being used by the cli client, so was subsequently orphaned. I wasn't aware that it was still being used by anyone. We have since done a lot of work to support multi platform candidates, which means that versions can vary between platforms (as they do for java). That said, Grails is a universal candidate that has consistent versions for all platforms.

I would need to implement a new endpoint specifically for this purpose that complies with out new API schema. I'll see what I can do to address this and report back here.

**Comment by marc0der** [comment]
Issue moved to [sdkman/sdkman-candidates #1](https://github.com/sdkman/sdkman-candidates/issues/1) via [**ZenHub**](https://www.zenhub.com/)
