### ISSUE TITLE
hdiutil verify fails

### ISSUE THREAD

**Issue by najor** [sdkman/sdkman-cli#582]
I was installing java 8u111 in a macOS Sierra and it seems hdituil has problem with the image is download, the image has errors or it is the incorrect image for Mac users:

> hdiutil: verify: unable to recognize "/Users/-------/.sdkman/tmp/g7nN1jFCkzWqIiR23RUqwSBhhBNea2Yh.bin" as a disk image. (image not recognized)
hdiutil: verify failed - image not recognized

Any ideas how can I fix this?

Cheers

**Comment by marc0der** [comment]
Just had a look into this and it seems like Oracle have removed all the Java 8 versions prior to 8u131 from their site. Since the Oracle site is where we download them from, they are no longer available for our users. Unfortunately, for now you would have to use 8u131.

We are planning on removing all Oracle JDKs soon, in favour of Azul Systems' Zulu OpenJDK implementations.

**Comment by najor** [comment]
Thanks for the update.
