### ISSUE TITLE
install success but can't use 

### ISSUE THREAD

**Issue by Kuangcp** [sdkman/sdkman-cli#592]
All done!

Please open a new terminal, or run the following in the existing one:

    source "/home/kcp/.sdkman/bin/sdkman-init.sh"

Then issue the following command:

    sdk help

Enjoy!!!
` then i run this command`
....$ source "/home/kcp/.sdkman/bin/sdkman-init.sh"
....$ sdk list
==== INTERNET NOT REACHABLE! ===================================================

 Some functionality is disabled or only partially available.
 If this persists, please enable the offline mode:

   $ sdk offline

================================================================================

This command is not available while offline.

**Comment by marc0der** [comment]
This is a usage issue, usually caused by a slow Internet connection. This can be remedied by tweaking the curl configuration of sdkman under ~/.sdkman/etc

In future, please try the Gitter chat channel for user issues before opening a github issue as per our guidelines on the README of this project.
