### ISSUE TITLE
Expected a proper numerical parameter

### ISSUE THREAD

**Issue by sivaswami** [sdkman/sdkman-cli#699]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [* ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:
OS: Ubuntu 18.04
curl version: 7.58.0

sdk i vertx
Downloading: vertx 3.7.1
In progress...
curl: option -C - --retry-max-time 60 --retry 0 --progress-bar --location: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by marc0der** [comment]
I've just tried installing the exact same without problems. If this was really a bug then many people would be very unhappy right now. You might be seeing this due to some behaviour in your shell.

OS: Manjaro Linux (up to date)
curl version: curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.2 nghttp2/1.36.0

In future, please follow the {contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) prior to opening an issue here. The above template also states clearly that issues not discussed will be closed immediately.

**Comment by nfekete** [comment]
I get the same error trying to install `sbt`.

```
sdk install sbt

Downloading: sbt 1.2.8

In progress...

curl: option -C - --retry-max-time 60 --retry 0 --progress-bar --location: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
mv: cannot stat '/home/nfekete/.sdkman/tmp/DObUtzC10NBWOMmqd3Abs2hTntReOc54.bin': No such file or directory
```

Environment: Ubuntu 18.04.3 LTS on Windows Subsystem for Linux
