### ISSUE TITLE
API Endpoints are not found

### ISSUE THREAD

**Issue by pipiobjo** [sdkman/sdkman-cli#724]
I tried to update my current installation via: 

```bash
sdk selfupdate force
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>404 Not Found</title></head>

```
Checking the script of https://get.sdkman.io/ 
```
SDKMAN_SERVICE="https://api.sdkman.io/2"
```

Curl the endpoint

```
curl https://api.sdkman.io/2
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.12</center>
</body>
</html>

```

But according to the status page everything should be okay
http://status.sdkman.io/

**Comment by marc0der** [comment]
Everything is up and running and hasn't been down at all (no alerts were fired).
The `SDKMAN_SERVICE` environment url is only the base URL, so you will always get a 404 from there.

In future, please follow the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) and chat to us on [slack](https://slack.sdkman.io) instead of opening an issue.

**Comment by AlanSanchezP** [comment]
I get this error when running `sdk selfupdate force` or `sdk list <candidate>`, which is weird considering that `sdk list` doesnt trigger any error.

```
bash: línea 1: html: No existe el archivo o el directorio
bash: línea 2: error sintáctico cerca del elemento inesperado `<'
'ash: línea 2: `<head><title>404 Not Found</title></head>
```
