### ISSUE TITLE
sdk install should be no-op if package already installed

### ISSUE THREAD

**Issue by galderz** [sdkman/sdkman-cli#731]
Right now this is an error, e.g.

    Stop! java 13.0.2.hs-adpt is already installed.

This makes it awkward for scripting

**Comment by galderz** [comment]
Or if you want to keep current behaviour, have a flag to make it no-op if already installed.

**Comment by hermitmaster** [comment]
I concur. Returning an error when you’re already in the desired state isn’t ideal.

**Comment by marc0der** [comment]
I think that everything that is not on the happy path should be a non-zero return code.

The reason here would be that your script can take an alternative action based on the return code of a command, allowing for smarter logic in scripts.

A non-zero return code is very easy to handle in a bash script btw, see the SDKMAN source code for lots of examples of such error handling.

**Comment by felipecassiors** [comment]
I think it should follow other "package managers" behavior. 

Homebrew, APT, NPM, Snap, all them return zero as status code when the package is already installed.

I'm currently writing a script that tries to ensure that a version of Java is installed, and because of this I have to write a try-catch and check if the output message contains "already installed". That's not good.

**Comment by marc0der** [comment]
@felipecassiors Since you are the forth person asking already, I'd be happy to accept a PR to change this behaviour. 

I know it is a cosmetic thing, but apart from the 0 return code, the red text to the tunes of `Stop! java 11.0.7.hs-adpt is already installed.` should also be changed to yellow for info.

**Comment by helpermethod** [comment]
This would also improve #785, as calling `sdk env install` would result in a non-zero return code if the last candidate is already installed.
