### ISSUE TITLE
Suggestion: Do not require Slack discussion prior posting issues

### ISSUE THREAD

**Issue by dragetd** [sdkman/sdkman-cli#753]
- [x] this is a new Feature Request, ~a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).~
- [ ] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

The current issue template states, that it is required to discuss things first in Slack before opening an issue. Otherwise the issue will be simply closed. This is a rather unconventional workflow compared to most other open source projects.

The reason stated is quality and validity of Issues. I assume it is to avoid 'unnecessary issues' that distract people. But this shifts the problem simply to 'unnecessary chat noise'. Instead, an Issue can be discussed, labeled and closed (even auto-closed with bots) if the quality is not acceptable, while still being available for reference (when new issues are reported, GitHub suggests old issues).

It might demotivate people from actually opening and addressing issues.

Also, Slack is a proprietary chat application with closed-source clients and annoyingly poor Linux support. As a developer and strong believer in OpenSource this very much puts me into that category of frustration when I want to raise issues with a project and then get such a parrying rule. Especially with a non-free, non-open chat protocol. There are alternatives with lower entry barriers, e.g. matrix.

The irony of this very issue is: I did not intend posting this issue without a chat and before the actual rule was removed, but I am failing since ~2 hours to join the Slack chat. When trying to get an invite, Slack will simply not send me the join-link to the workspace to my work email (Outlook). Not in Junk… no idea if it is Outlook or Slack messing up here. But frankly I am not motivated to debug this. That is why I opened this issue here, hoping to not step on anyone's toes.

Edit: It was Outlook and I now got the mail. Closing this issue, bringing it up in Slack first…

**Comment by marc0der** [comment]
Hi @dragetd,

Thought I'd answer you here as this affects the Github workflow most of all.

This project started out as an itch that I had many years ago. I wanted to install SDKs on my machine, got frustrated with the laborious process, and eventually decided to write a small tool that would scratch my itch. That was about 7 years ago, and I never dreamed that it would grow into such a huge thriving community.

Sometime ago, I started having issues keeping up with the continuous flood of Github issues that were pouring in. The problem was, most of them weren't issues but simply questions. Most of the time, people were'n't bothering to read our usage pages or even consult the FAQ. Easier to just hit the new issue button right?

As a result of the deluge of issues, and me spending my precious free time constantly answering them, I decided to bring this into a chat environment. This has worked wonders, and has given me most of my precious free time back! Initially we had a Gitter chat room, but that simply didn't work well enough. Enter Slack!

Because every single organisation that I work with uses Slack (and many other cool OSS projects I'm affiliated with too), I decided to open one for SDKMAN. People love it. I have stood up a Slackin server which eases the onboarding process and gets people collaborating within minutes. Now I am no longer the bottleneck, and everyone gets to help everyone else! I also get to respond to user issues / questions a lot faster, and am able to triage real issues and feature requests into Github issues that everyone can get onboard with and contribute to.

Further to your gripes with Slack. You say that Slack has issues on Linux. I beg to differ. I have been  using Linux for close on 20 years. I use no other operating system for that matter. I use Slack on my Arch Linux laptop every single day of my life and _never_ have any issues with their native app. It's simply great. I'm sorry to hear that you have been having issues with it, and encourage you to give it another spin.

The truth is, everyone uses Slack these days for better or worse. The whole idea of starting the Slack community was for the sake of inclusion. Everyone has it on their phone and on their laptop. If someone has an issue, they simply go to the user-issues channel and drop a note. Most likely I (or one of the many helpful community members) will get back to them with a response shortly.

Even though I am open to change and improvement, I'm finding that this approach has worked out very well and has certainly helped me manage this project a lot better. I'm hesitant to go back to the old workflow of facing the barrage of issues in my mailbox again every morning, but am certainly open for improving the templates (and making them friendlier). Anyway, hope to see you on Slack so we can continue the converation!

**Comment by dragetd** [comment]
In Slack, Marco explained the burden of new issues which are not really issues, but questions and discussions that take time to evaluate and not easy to keep up for just him.

He is open for alternative ideas, but so far the Slack approach has helped. He suggested to reopen the issue. Maybe someone else has a new idea.

I suggested extending the issue template to distinguish between issues and questions, allowing easier filtering instead. I'll open a PR sometime later with a suggestions that can be discussed there. :)

**Comment by rgoldberg** [comment]
Maybe the issue template could tell people to only file bugs reports & feature requests in Github (after ensuring they aren't duplicating anything), and to ask for support on Slack.  That would hopefully prevent Github issues from being used inappropriately, but could keep bug reports & feature requests in Github so they're more easily searchable, and so that info doesn't get lost when copying an approved issue from Slack to Github (plus save the time of diligently copying from Slack to Github).

It seems like the best of both worlds to me.

**Comment by Abhinav1217** [comment]
HI, 
When I try to create an account on slack, It askes me to create a workespace, I am lone developer not affiliated to any organization. Some OSS projects have IRC or telegram chat channel which is more targeted towards individuals not organization. Is there any other place for discussion other than slack. I have a weird issue with sdkman, and I understand that it may not be a bug but some configuration issue, so discussing it before submitting issue makes sense. But having to create an account on slack which is asking me to create a workspace and add team...?

**Comment by marc0der** [comment]
Sounds like you aren't using our Slackin server @Abhinav1217, you simply follow the link under the Socialise menu on our website and everything is done for you.

Also, if you follow this simple flow you won't be prompted to create a workspace but simply join the SDKMAN workspace.

**Comment by Abhinav1217** [comment]
Thanks, I followed the link and added myself to the sdkman workspace. I posted my issues in the #user-issue channel.

**Comment by marc0der** [comment]
Closing this issue as the new workflow has now been merged.
