### ISSUE TITLE
Bug: "sdk list java" returns a 404

### ISSUE THREAD

**Issue by drewandersen** [sdkman/sdkman-cli#772]
**Bug report**
Downloaded `sdkman` using the instructions from the website. Ran `sdk list java` and received the following error:
```
$ sdk list java
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.12</center>
</body>
</html>
```

**System info**
Ubuntu 20.04 (5.4.0-40-generic kernel)
5.0.16(1)-release
SDKMAN 5.5.12+269

**Comment by marc0der** [comment]
Hi @drewandersen, can I ask you to try upgrading SDKMAN to the latest version please?

The current version is `5.8.3+506`, and the API has changed a lot since `5.5.12` (released almost 3 years ago).

Please let me know how that goes.

**Comment by marc0der** [comment]
No response and cannot replicate so closing this issue for now.

**Comment by momrak** [comment]
Hi!
I get this same error myself, but only when running sdkman through a proxy (here a Nexus raw proxy), could that be the issue here?

I use sdkman version: 5.12.2 on a company computer that is airgapped. We set up a proxy for the requests and have changed the environement variable `SDKMAN_CANDIDATES_API=<proxyurl>` and the proxy then points to `https://api.sdkman.io/2`.

This works perfectly for all candidates except java. I am also able to install java if I look up the version from another "normal" connected computer, so it is only when running `sdk list java` i get this issue. I attached an image showing the difference when running `sdk list maven` and `sdk list java`

I am aware this is not the default supported way of using sdkman, but as it works for all all candidates (at least the ones I have tested), could there be some kind of bug? Do you have any recommendations or fixes in mind for this, @marc0der ? :)

Best regards,
Jon Magnus

![sdkman-java-404-anon](https://user-images.githubusercontent.com/6552049/128322994-56128205-e4e7-4c76-a810-17bb8d9c1c83.png)
