### ISSUE TITLE
Bug: upgrade message does not contain the new version

### ISSUE THREAD

**Issue by lutzhorn** [sdkman/sdkman-cli#786]
**Bug report**

The message about a possible upgrade of sdkman as generated by  `sdk update` does not include the version that can be upgraded to:

```
The current version is , but you have 5.8.3+506.
```

**To reproduce**

```
% sdk update
==== BROADCAST =================================================================
* 2020-08-05: Gradle 6.6-rc-6 released on SDKMAN! #gradle
* 2020-08-03: Gradle 6.6-rc-5 released on SDKMAN! #gradle
* 2020-08-02: Jbang 0.36.1 released on SDKMAN! Checkout https://github.com/jbangdev/jbang/releases/tag/v0.36.1. Follow @jbangdev #jbang
================================================================================

Adding new candidates(s): gradleprofiler http4k

Please open a new terminal now...


ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.8.3+506.

Would you like to upgrade now? (Y/n): n
Not upgrading today...
```

**System info**

```
% zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by marc0der** [comment]
This usually occurs when a login shell (as opposed to an interactive shell) is being used. You can try switching to interactive in your terminal settings and the problem should go away.

**Comment by Woodham** [comment]
Hi @marc0der , sorry for bringing this back up but I have the same issue and I don't quite understand your suggested fix.

on MacOS all shells are by default both login shells _and_ interactive shells. They must all be login shells because MacOS doesn't run `.profile` or `.bash_profile` on startup like linux systems and if they weren't login shells then they would be broken.

Am I misunderstanding something? My understanding is login shells and interactive shells are not mutually exclusive.
