### ISSUE TITLE
Bug: sdk list in offline mode does not work as documented

### ISSUE THREAD

**Issue by matthieu-vergne** [sdkman/sdkman-cli#788]
**Bug report**
The [documentation](https://sdkman.io/usage#offline) says:
```
$ sdk list
------------------------------------------------------------
Offline Mode: only showing installed groovy versions
------------------------------------------------------------
> 2.4.4
* 2.4.3
------------------------------------------------------------
* - installed
> - currently in use
------------------------------------------------------------
```
I have installed 2 Java SDKs. Despite that, if I lose the connection or explicitly set the offline mode:
```
$ sdk list
This command is not available while offline.
```

Meanwhile, executing `sdk list java` while offline does list the installed Java SDKs. But if I want to know everything installed, `sdk list` just does not work.

**To reproduce**
Nothing specific beside installing Sdkman, installing few SDKs and executing `sdk list` while offline.

**System info**
- OS: Kubuntu 18.04
- Shell and version: bash 4.4.20(1)-release
- Sdkman version: 5.9.0+555

**Comment by marc0der** [comment]
Hi @matthieu-vergne, this is simply a typo on the website, it should state `sdk list groovy`. The `list` command without qualifier will not work in offline mode as it is completely rendered on the serverside.

Also worth noting that the [list command without qualifier](https://sdkman.io/usage#listcandidates) does not show anything about available or installed versions, but only information about candidates on sdkman. Hope this helps.

I'll release a fix for the website shortly.

**Comment by marc0der** [comment]
This has been corrected on the website and will be released shortly.

**Comment by matthieu-vergne** [comment]
Well, it does not really help since the feature is not there in the end. The lack of consistency of the list command also makes it confusing.

I don't want to play the newbie who is here only to complain (I am familiar with open source, so I know I am not here to require anything from you and if I really want something I can just make a PR), but I am currently starting using sdkman to see if we can use it in our team to facilitate our work. And it was quite a turndown to be unable to use it soon after installation, when I lost my connection (which happens quite frequently since the overload due to teleworking). The overall idea is really nice, but facing confusing commands and limited offline support so soon in my use just give it a feel of beta. It makes it hard to present to the team with a positive mind. It looks easier to just use `update-alternatives` again.

I looked at other issues. I read here and there that the offline mode was prone to be replaced and discussions about managing better the list of installed stuff. So I hope to see some evolutions on that matter soon. Again, not asking you anything to compensate. Only sharing the experience I had and expectations for the future.

Hope it makes sense.

**Comment by marc0der** [comment]
Sad to hear that you think our commands are inconsistent, and that it feels like a beta to you. I went to great lengths building these features to be as consistent as possible and tried involving the community every step of the way. A BDD approach was taken to specify each feature and was presented to the community to allow feedback before development occurred. You certainly are the first to tell me that the CLI command syntax is inconsistent, and that it feels like a beta. You seem to make this leap based on a one word typo on the website.

I would also be the first to tell you that the offline mode is broken and does not meet my expectation. It was one of the very early features that I introduced and probably not my proudest moment. The fact that it doesn't degrade well is a known issue, but because a tiny minority of our users actually rely on offline mode, it has not been a high priority to fix. This tool relies heavily on the internet, just like 99% of the other tools that you use every single day to develop software.

Instead of the offline mode, the rewrite of SDKMAN will not have an offline mode. It will be offline by default. It will rely on state being pulled down into a local cache much like `apt` or `git` does. That means that calls will not be made for every command as it currently occurs.

Until the rewrite happens, we are unfortunately stuck with a broken offline mode. If this is a huge issue for you, I welcome pull requests and contributions to make this better for yourself and any other users that might have this issue. If not, you are very welcome to use any other tool that does meet your requirements.

**Comment by matthieu-vergne** [comment]
In my case, offline should be at least as important as online, so indeed the broken offline mode is a main issue. Although I understand it is not the case for most people. I am just part of the minority.

The inconsistency is of course not based on a single documentation typo, but on the fact that:
- offline mode is a main use to me
- `list` is a must have for any one

This combination made the very basic use of sdkman broken, thus the bad experience.

What I expected from a well designed program is to be discoverable:
- `sdk` = list possible commands (list, use, etc.)
- `sdk list` = list available types of SDKs (java, groovy, etc.)
- `sdk list java` = list available java SDKs (8.xxx, 11.xxx, etc.)

In offline mode, you have the first, you have the third, but you don't have the second. So you get stuck there and cannot use the tool at all without reading the documentation. And since `sdk help` only provides the output of `sdk` (`sdk help list` gives nothing) I must rely on the online documentation to know the details. When you already have to face an offline mode, reading the online documentation is of course not the easiest thing to do.

The typo only made it harder, since the documentation said that `sdk list` was what I needed, but it was not. And I had to browse the issues (online too) to figure out it was `sdk list java`.

So the very reason of the feedback is surely the low priority, broken offline mode. And reading that sdkman should be rewritten for offline becoming the default is a good thing. I hope you will consider discoverability to be a high priority too, so we can do without the online documentation for a better offline support.

I already participate in several projects on GitHub, and it would be a pleasure to contribute here too. But 2/3 of the code is in Gherkin and Groovy, which I don't know, and 1/3 is in shell, which I know but not master. So I don't have the skill to contribute efficiently. And since sdkman, in my case, mainly facilitates the use of `update-aternatives` and `JAVA_HOME`, I am afraid the cost-benefit is not in favor of a contribution.
