### ISSUE TITLE
Bug: [Version info for btrace incorrectly compared 2.1.0 < 2.0.3]

### ISSUE THREAD

**Issue by soberich** [sdkman/sdkman-cli#869]
**Bug report**
on `sdk upgrade`
see below

**To reproduce**

```
sdk upgrade btrace

Upgrade:
btrace (2.1.0 < 2.0.3)

Upgrade candidate(s) and set latest version(s) as default? (Y/n): n
```

**System info**
```
zsh 5.8 (x86_64-apple-darwin20.1.0)
```

**Comment by marc0der** [comment]
Hi @soberich, the problem here is a combination of wording and an incorrect default version setting in the database. The folks who contributed this code assumed that the latest version would always be the default. When the vendor then publishes a new version without remembering to update the default version, you see the above.

I suggest two things to remedy this:
* Change the wording here. It isn't valid to say that `x < y`, but rather that the default version is x and the installed version is `y`.
* Contact the btrace maintainer(s) to update the default version to `2.1.0`.

**Comment by marc0der** [comment]
The wording has now been improved. Please feel free to raise an issue with the btrace team to update the default version to the latest available.
