### ISSUE TITLE
Question: how to force JAVA_HOME to point to install and not symlink 

### ISSUE THREAD

**Issue by viniciusccarvalho** [sdkman/sdkman-cli#904]
- [x] I have checked [the documentation](https://sdkman.io/usage)
- [x] I have done a quick search in [past issues](https://github.com/rclone/rclone/issues?q=) or [Stack Overflow](https://stackoverflow.com/questions/tagged/sdkman) for similar problems
- [x] I have brought up a conversation in the [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues)

**Question**
I have been having this issue with my new machine, and it is really driving me nuts :( 
SDK sets java home to `.sdkman/candidates/java/current` but I'm having issues with intellij and gradle, because intellij is resolving the seemlink to the real path, and sending it to gradle daemon which then refuses to execute due mismatch java home location. 

I keep needing to manually set the java_home to the real path everytime I start a new session, is there a way to automatically do this? I was hoping even if a few shell script commands to be added to my .profile to force change java home to the path of the current selected. This is really hurting me currently, I'd appreciate any help.

Cheers

**System info**
Mac OS BigSur
zsh 5.8
SDKMAN 5.11.0+644
-->

**Comment by ecerruti** [comment]
I haven't run into this issue (I use Gradle from sdkman). But to answer your question this works for me if you are using the typical sdkman install, otherwise modify to your usage...

- After this entry in whatever zsh startup file you have it

```
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
```

- Add the following, or where ever you set `JAVA_HOME` in your startup files, if `JAVA_HOME` is not set use the actual path instead, e.g. `~/.sdkman/candidates/java/current`

```
export JAVA_HOME=$(greadlink -m $JAVA_HOME)
```

**NOTES**

- `greadlink` is from [Homebrew](https://brew.sh), so adjust accordingly on whether you symlinked with the `g` prefix or not
  - Run `greadlink --help` to see the differences between `-e`, `-f` and `-m`
  - The `/usr/bin/readlink` is not very useful and probably won't work (mine only has a `-n` option)
- Not an sdkman issue - YMMV
  - `sdk <command> java <candidate>` can result in unexpected behavior with this setup, so you may have to run `greadline` from the command line when doing on-the-fly changes

**Comment by viniciusccarvalho** [comment]
Thank you @ecerruti that worked just fine.

**Comment by Talbot3** [comment]
>   * `sdk <command> java <candidate>`可能会导致此设置出现意外行为，因此`greadline`在进行实时更改时可能必须从命令行运行

mark here for other people:

```
brew install coreutils
```
