### ISSUE TITLE
Bug: /usr/libexec/java_home does not find current Java on macOS Big Sur

### ISSUE THREAD

**Issue by timkofu** [sdkman/sdkman-cli#952]
The above command does not not find the `current`  Java as shown by `sdk current java`.

Homebrew has the following OpenJDK post-installation instruction:
```
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```

Is there a similar procedure for sdkman that will always link to the current Java?

**Comment by marc0der** [comment]
Please read the [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/8d7d101eecbf62fb0e9bf05be238419a58ce0e28/CONTRIBUTING.md) before opening an issue.

**Comment by timkofu** [comment]
Read them, they don't explain why this issues was just brushed off.

**Comment by marc0der** [comment]
Hi @timkofu, 

Because all of us maintaining sdkman are volunteers we try to keep the Github issues to an absolute minimum. For this reason, we ask people to chat with us on Slack before opening issues here so that only true bugs appear here. The reason I closed this issue was that it was not a bug, and the template (that provides us with the context we need to replicate/solve real issues) was deleted. Apologies if this wasn't clear enough, I'll make sure that it is more clearly stated.

The issue template that you deleted did clearly say the following:

> If you are unsure if it is a bug, then consider using the Slack chat before creating a new issue. Please understand, that we cannot offer regular support through GitHub issues and might close the issue if it is not an actual bug!

That said, I'll make it clearer that the template should not be deleted.

Your question has cropped up many times before, so we have an [entry on our FAQ](https://github.com/sdkman/sdkman-cli/wiki/FAQ#on-mac-usrlibexecjava_home-does-not-detect-alternatives-installed-by-sdkman-what-can-i-do) that explains why this does not work.

**Comment by timkofu** [comment]
Hi @marc0der 

Thanks for clearing it up. 

I would seem the `NetBeans` installer is using the result of `/usr/libexec/java_home` to work out where Java is, and refuses to install if it's empty. Linking the Hombrew OpenJDK there worked, but I chose to go with the Oracle JDK as it's noticeably snappier with GUI apps on my machine.

All the same, thanks for the comprehensive answer, and the hard work that's SDKMan.
